// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puzfnwfimroyapapfyhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1emZud2ZpbXJveWFwYXBmeWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEwNTI3NzIsImV4cCI6MjA3NjYyODc3Mn0.Wz_rfiahn3WycGmmnOcq08E2XIB0MNMFWPKNj31LbIw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});